// Wire protocol for the moonshine serve sidecar's gRPC transport. Mirrors
// internal/serve/event's Go types (see docs/serve-sidecar.md section 8 --
// this is the frozen contract; keep it in sync with event.go). The
// WebSocket transport (ws.go) speaks the same information as plain JSON;
// this proto is for typed/codegen'd clients.
//
// Regenerate with `make proto` after editing this file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/serve/serve.proto

package servepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceSidecar_Stream_FullMethodName = "/moonshine.serve.v1.VoiceSidecar/Stream"
)

// VoiceSidecarClient is the client API for VoiceSidecar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VoiceSidecar is the single bidirectional-streaming RPC a client opens: it
// sends ActionRequests in and receives Events out, for as long as the
// stream is held open. One stream corresponds to one Hub subscription
// (see grpc.go).
type VoiceSidecarClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionRequest, Event], error)
}

type voiceSidecarClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceSidecarClient(cc grpc.ClientConnInterface) VoiceSidecarClient {
	return &voiceSidecarClient{cc}
}

func (c *voiceSidecarClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ActionRequest, Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceSidecar_ServiceDesc.Streams[0], VoiceSidecar_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionRequest, Event]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceSidecar_StreamClient = grpc.BidiStreamingClient[ActionRequest, Event]

// VoiceSidecarServer is the server API for VoiceSidecar service.
// All implementations must embed UnimplementedVoiceSidecarServer
// for forward compatibility.
//
// VoiceSidecar is the single bidirectional-streaming RPC a client opens: it
// sends ActionRequests in and receives Events out, for as long as the
// stream is held open. One stream corresponds to one Hub subscription
// (see grpc.go).
type VoiceSidecarServer interface {
	Stream(grpc.BidiStreamingServer[ActionRequest, Event]) error
	mustEmbedUnimplementedVoiceSidecarServer()
}

// UnimplementedVoiceSidecarServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceSidecarServer struct{}

func (UnimplementedVoiceSidecarServer) Stream(grpc.BidiStreamingServer[ActionRequest, Event]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedVoiceSidecarServer) mustEmbedUnimplementedVoiceSidecarServer() {}
func (UnimplementedVoiceSidecarServer) testEmbeddedByValue()                      {}

// UnsafeVoiceSidecarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceSidecarServer will
// result in compilation errors.
type UnsafeVoiceSidecarServer interface {
	mustEmbedUnimplementedVoiceSidecarServer()
}

func RegisterVoiceSidecarServer(s grpc.ServiceRegistrar, srv VoiceSidecarServer) {
	// If the following call panics, it indicates UnimplementedVoiceSidecarServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceSidecar_ServiceDesc, srv)
}

func _VoiceSidecar_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceSidecarServer).Stream(&grpc.GenericServerStream[ActionRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceSidecar_StreamServer = grpc.BidiStreamingServer[ActionRequest, Event]

// VoiceSidecar_ServiceDesc is the grpc.ServiceDesc for VoiceSidecar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceSidecar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moonshine.serve.v1.VoiceSidecar",
	HandlerType: (*VoiceSidecarServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _VoiceSidecar_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/serve/serve.proto",
}
