// Wire protocol for the moonshine serve sidecar's gRPC transport. Mirrors
// internal/serve/event's Go types (see docs/serve-sidecar.md section 8 --
// this is the frozen contract; keep it in sync with event.go). The
// WebSocket transport (ws.go) speaks the same information as plain JSON;
// this proto is for typed/codegen'd clients.
//
// Regenerate with `make proto` after editing this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/serve/serve.proto

package servepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is a discriminated union of everything the sidecar can push to a
// subscriber, mirroring event.Kind / the WebSocket transport's
// wireEnvelope. Exactly one field is set.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Transcript
	//	*Event_Display
	//	*Event_ActionResult
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_serve_serve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serve_serve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_serve_serve_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTranscript() *TranscriptEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Transcript); ok {
			return x.Transcript
		}
	}
	return nil
}

func (x *Event) GetDisplay() *DisplayCard {
	if x != nil {
		if x, ok := x.Payload.(*Event_Display); ok {
			return x.Display
		}
	}
	return nil
}

func (x *Event) GetActionResult() *ActionResult {
	if x != nil {
		if x, ok := x.Payload.(*Event_ActionResult); ok {
			return x.ActionResult
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Transcript struct {
	Transcript *TranscriptEvent `protobuf:"bytes,1,opt,name=transcript,proto3,oneof"`
}

type Event_Display struct {
	Display *DisplayCard `protobuf:"bytes,2,opt,name=display,proto3,oneof"`
}

type Event_ActionResult struct {
	ActionResult *ActionResult `protobuf:"bytes,3,opt,name=action_result,json=actionResult,proto3,oneof"`
}

func (*Event_Transcript) isEvent_Payload() {}

func (*Event_Display) isEvent_Payload() {}

func (*Event_ActionResult) isEvent_Payload() {}

// Line mirrors moonshine.Line's wire-relevant fields (internal/moonshine/stt.go).
// Word/SpeakerSpan details are intentionally omitted from v1 of this proto
// (available via the WebSocket/JSON transport, which carries the full Go
// struct) to keep the gRPC surface minimal; extend here if a gRPC consumer
// needs them.
type Line struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	StartTime      float32                `protobuf:"fixed32,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration       float32                `protobuf:"fixed32,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Id             uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	IsComplete     bool                   `protobuf:"varint,5,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	IsUpdated      bool                   `protobuf:"varint,6,opt,name=is_updated,json=isUpdated,proto3" json:"is_updated,omitempty"`
	IsNew          bool                   `protobuf:"varint,7,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	HasTextChanged bool                   `protobuf:"varint,8,opt,name=has_text_changed,json=hasTextChanged,proto3" json:"has_text_changed,omitempty"`
	SpeakerLabel   string                 `protobuf:"bytes,9,opt,name=speaker_label,json=speakerLabel,proto3" json:"speaker_label,omitempty"` // derived, see moonshine.Line.SpeakerLabel()
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_internal_serve_serve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serve_serve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_internal_serve_serve_proto_rawDescGZIP(), []int{1}
}

func (x *Line) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Line) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Line) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Line) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Line) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *Line) GetIsUpdated() bool {
	if x != nil {
		return x.IsUpdated
	}
	return false
}

func (x *Line) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *Line) GetHasTextChanged() bool {
	if x != nil {
		return x.HasTextChanged
	}
	return false
}

func (x *Line) GetSpeakerLabel() string {
	if x != nil {
		return x.SpeakerLabel
	}
	return ""
}

type SessionSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LinesFinalized    int32                  `protobuf:"varint,1,opt,name=lines_finalized,json=linesFinalized,proto3" json:"lines_finalized,omitempty"`
	AvgTimeToFinalMs  int64                  `protobuf:"varint,2,opt,name=avg_time_to_final_ms,json=avgTimeToFinalMs,proto3" json:"avg_time_to_final_ms,omitempty"`
	MaxTimeToFinalMs  int64                  `protobuf:"varint,3,opt,name=max_time_to_final_ms,json=maxTimeToFinalMs,proto3" json:"max_time_to_final_ms,omitempty"`
	AvgRevisions      float64                `protobuf:"fixed64,4,opt,name=avg_revisions,json=avgRevisions,proto3" json:"avg_revisions,omitempty"`
	MaxRevisions      int32                  `protobuf:"varint,5,opt,name=max_revisions,json=maxRevisions,proto3" json:"max_revisions,omitempty"`
	AvgStabilityRatio float64                `protobuf:"fixed64,6,opt,name=avg_stability_ratio,json=avgStabilityRatio,proto3" json:"avg_stability_ratio,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_internal_serve_serve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serve_serve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_internal_serve_serve_proto_rawDescGZIP(), []int{2}
}

func (x *SessionSummary) GetLinesFinalized() int32 {
	if x != nil {
		return x.LinesFinalized
	}
	return 0
}

func (x *SessionSummary) GetAvgTimeToFinalMs() int64 {
	if x != nil {
		return x.AvgTimeToFinalMs
	}
	return 0
}

func (x *SessionSummary) GetMaxTimeToFinalMs() int64 {
	if x != nil {
		return x.MaxTimeToFinalMs
	}
	return 0
}

func (x *SessionSummary) GetAvgRevisions() float64 {
	if x != nil {
		return x.AvgRevisions
	}
	return 0
}

func (x *SessionSummary) GetMaxRevisions() int32 {
	if x != nil {
		return x.MaxRevisions
	}
	return 0
}

func (x *SessionSummary) GetAvgStabilityRatio() float64 {
	if x != nil {
		return x.AvgStabilityRatio
	}
	return 0
}

// TranscriptEvent mirrors event.TranscriptEvent.
type TranscriptEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Lines            []*Line                `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	FinalizedLineIds []uint64               `protobuf:"varint,2,rep,packed,name=finalized_line_ids,json=finalizedLineIds,proto3" json:"finalized_line_ids,omitempty"`
	TtftMs           int64                  `protobuf:"varint,3,opt,name=ttft_ms,json=ttftMs,proto3" json:"ttft_ms,omitempty"`
	ElapsedMs        int64                  `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	PollLatencyMs    int64                  `protobuf:"varint,5,opt,name=poll_latency_ms,json=pollLatencyMs,proto3" json:"poll_latency_ms,omitempty"`
	Summary          *SessionSummary        `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"` // unset unless done == true
	Done             bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	Err              string                 `protobuf:"bytes,8,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TranscriptEvent) Reset() {
	*x = TranscriptEvent{}
	mi := &file_internal_serve_serve_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptEvent) ProtoMessage() {}

func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serve_serve_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptEvent.ProtoReflect.Descriptor instead.
func (*TranscriptEvent) Descriptor() ([]byte, []int) {
	return file_internal_serve_serve_proto_rawDescGZIP(), []int{3}
}

func (x *TranscriptEvent) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *TranscriptEvent) GetFinalizedLineIds() []uint64 {
	if x != nil {
		return x.FinalizedLineIds
	}
	return nil
}

func (x *TranscriptEvent) GetTtftMs() int64 {
	if x != nil {
		return x.TtftMs
	}
	return 0
}

func (x *TranscriptEvent) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *TranscriptEvent) GetPollLatencyMs() int64 {
	if x != nil {
		return x.PollLatencyMs
	}
	return 0
}

func (x *TranscriptEvent) GetSummary() *SessionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *TranscriptEvent) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *TranscriptEvent) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// DisplayCard mirrors event.DisplayCard. data is opaque JSON (kept as
// bytes rather than google.protobuf.Struct to avoid a well-known-types
// dependency for what is, in v1, a rarely-machine-parsed payload).
type DisplayCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // raw JSON, same content as event.DisplayCard.Data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayCard) Reset() {
	*x = DisplayCard{}
	mi := &file_internal_serve_serve_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayCard) ProtoMessage() {}

func (x *DisplayCard) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serve_serve_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayCard.ProtoReflect.Descriptor instead.
func (*DisplayCard) Descriptor() ([]byte, []int) {
	return file_internal_serve_serve_proto_rawDescGZIP(), []int{4}
}

func (x *DisplayCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DisplayCard) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DisplayCard) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DisplayCard) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ActionRequest mirrors event.ActionRequest. args is the verb-specific
// payload, encoded as raw JSON bytes (same reasoning as DisplayCard.data)
// so new verbs never require a proto schema change.
type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Verb          string                 `protobuf:"bytes,2,opt,name=verb,proto3" json:"verb,omitempty"`
	Args          []byte                 `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"` // raw JSON, same content as event.ActionRequest.Args
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_internal_serve_serve_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serve_serve_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_serve_serve_proto_rawDescGZIP(), []int{5}
}

func (x *ActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionRequest) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *ActionRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

// ActionResult mirrors event.ActionResult.
type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_internal_serve_serve_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serve_serve_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_internal_serve_serve_proto_rawDescGZIP(), []int{6}
}

func (x *ActionResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ActionResult) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_internal_serve_serve_proto protoreflect.FileDescriptor

const file_internal_serve_serve_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/serve/serve.proto\x12\x12moonshine.serve.v1\"\xdf\x01\n" +
	"\x05Event\x12E\n" +
	"\n" +
	"transcript\x18\x01 \x01(\v2#.moonshine.serve.v1.TranscriptEventH\x00R\n" +
	"transcript\x12;\n" +
	"\adisplay\x18\x02 \x01(\v2\x1f.moonshine.serve.v1.DisplayCardH\x00R\adisplay\x12G\n" +
	"\raction_result\x18\x03 \x01(\v2 .moonshine.serve.v1.ActionResultH\x00R\factionResultB\t\n" +
	"\apayload\"\x8b\x02\n" +
	"\x04Line\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x02R\tstartTime\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x02R\bduration\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\x12\x1f\n" +
	"\vis_complete\x18\x05 \x01(\bR\n" +
	"isComplete\x12\x1d\n" +
	"\n" +
	"is_updated\x18\x06 \x01(\bR\tisUpdated\x12\x15\n" +
	"\x06is_new\x18\a \x01(\bR\x05isNew\x12(\n" +
	"\x10has_text_changed\x18\b \x01(\bR\x0ehasTextChanged\x12#\n" +
	"\rspeaker_label\x18\t \x01(\tR\fspeakerLabel\"\x93\x02\n" +
	"\x0eSessionSummary\x12'\n" +
	"\x0flines_finalized\x18\x01 \x01(\x05R\x0elinesFinalized\x12.\n" +
	"\x14avg_time_to_final_ms\x18\x02 \x01(\x03R\x10avgTimeToFinalMs\x12.\n" +
	"\x14max_time_to_final_ms\x18\x03 \x01(\x03R\x10maxTimeToFinalMs\x12#\n" +
	"\ravg_revisions\x18\x04 \x01(\x01R\favgRevisions\x12#\n" +
	"\rmax_revisions\x18\x05 \x01(\x05R\fmaxRevisions\x12.\n" +
	"\x13avg_stability_ratio\x18\x06 \x01(\x01R\x11avgStabilityRatio\"\xb3\x02\n" +
	"\x0fTranscriptEvent\x12.\n" +
	"\x05lines\x18\x01 \x03(\v2\x18.moonshine.serve.v1.LineR\x05lines\x12,\n" +
	"\x12finalized_line_ids\x18\x02 \x03(\x04R\x10finalizedLineIds\x12\x17\n" +
	"\attft_ms\x18\x03 \x01(\x03R\x06ttftMs\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs\x12&\n" +
	"\x0fpoll_latency_ms\x18\x05 \x01(\x03R\rpollLatencyMs\x12<\n" +
	"\asummary\x18\x06 \x01(\v2\".moonshine.serve.v1.SessionSummaryR\asummary\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\x12\x10\n" +
	"\x03err\x18\b \x01(\tR\x03err\"_\n" +
	"\vDisplayCard\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"G\n" +
	"\rActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04verb\x18\x02 \x01(\tR\x04verb\x12\x12\n" +
	"\x04args\x18\x03 \x01(\fR\x04args\"@\n" +
	"\fActionResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err2Z\n" +
	"\fVoiceSidecar\x12J\n" +
	"\x06Stream\x12!.moonshine.serve.v1.ActionRequest\x1a\x19.moonshine.serve.v1.Event(\x010\x01B9Z7github.com/ghchinoy/moonshine-go/internal/serve/servepbb\x06proto3"

var (
	file_internal_serve_serve_proto_rawDescOnce sync.Once
	file_internal_serve_serve_proto_rawDescData []byte
)

func file_internal_serve_serve_proto_rawDescGZIP() []byte {
	file_internal_serve_serve_proto_rawDescOnce.Do(func() {
		file_internal_serve_serve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_serve_serve_proto_rawDesc), len(file_internal_serve_serve_proto_rawDesc)))
	})
	return file_internal_serve_serve_proto_rawDescData
}

var file_internal_serve_serve_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_serve_serve_proto_goTypes = []any{
	(*Event)(nil),           // 0: moonshine.serve.v1.Event
	(*Line)(nil),            // 1: moonshine.serve.v1.Line
	(*SessionSummary)(nil),  // 2: moonshine.serve.v1.SessionSummary
	(*TranscriptEvent)(nil), // 3: moonshine.serve.v1.TranscriptEvent
	(*DisplayCard)(nil),     // 4: moonshine.serve.v1.DisplayCard
	(*ActionRequest)(nil),   // 5: moonshine.serve.v1.ActionRequest
	(*ActionResult)(nil),    // 6: moonshine.serve.v1.ActionResult
}
var file_internal_serve_serve_proto_depIdxs = []int32{
	3, // 0: moonshine.serve.v1.Event.transcript:type_name -> moonshine.serve.v1.TranscriptEvent
	4, // 1: moonshine.serve.v1.Event.display:type_name -> moonshine.serve.v1.DisplayCard
	6, // 2: moonshine.serve.v1.Event.action_result:type_name -> moonshine.serve.v1.ActionResult
	1, // 3: moonshine.serve.v1.TranscriptEvent.lines:type_name -> moonshine.serve.v1.Line
	2, // 4: moonshine.serve.v1.TranscriptEvent.summary:type_name -> moonshine.serve.v1.SessionSummary
	5, // 5: moonshine.serve.v1.VoiceSidecar.Stream:input_type -> moonshine.serve.v1.ActionRequest
	0, // 6: moonshine.serve.v1.VoiceSidecar.Stream:output_type -> moonshine.serve.v1.Event
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_serve_serve_proto_init() }
func file_internal_serve_serve_proto_init() {
	if File_internal_serve_serve_proto != nil {
		return
	}
	file_internal_serve_serve_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Transcript)(nil),
		(*Event_Display)(nil),
		(*Event_ActionResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_serve_serve_proto_rawDesc), len(file_internal_serve_serve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_serve_serve_proto_goTypes,
		DependencyIndexes: file_internal_serve_serve_proto_depIdxs,
		MessageInfos:      file_internal_serve_serve_proto_msgTypes,
	}.Build()
	File_internal_serve_serve_proto = out.File
	file_internal_serve_serve_proto_goTypes = nil
	file_internal_serve_serve_proto_depIdxs = nil
}
