// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PushPCMChunk(arg1) {
  return window['go']['main']['App']['PushPCMChunk'](arg1);
}

export function StartStream(arg1, arg2) {
  return window['go']['main']['App']['StartStream'](arg1, arg2);
}

export function StopStream() {
  return window['go']['main']['App']['StopStream']();
}

export function TranscribeFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranscribeFile'](arg1, arg2, arg3);
}
