// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function PushPCMChunk(arg1:Array<number>):Promise<Array<main.LineOutput>>;

export function StartStream(arg1:string,arg2:string):Promise<void>;

export function StopStream():Promise<void>;

export function TranscribeFile(arg1:string,arg2:string,arg3:string):Promise<main.BatchOutput>;
